### ISSUE TITLE
Deprecation of synchronous methods in pyz3r

### ISSUE THREAD

**Issue by tcprescott** [Feneg/pyz3rui#1]
Starting with version 4.0 of pyz3r (which will be the version compatible with v31), only asyncio will be supported.  I was having to maintain two different version of the application, and I mostly wrote this to support Discord and IRC bots, which are async.

Sorry for the inconvenience, but I thought I'd at least warn you about this in advance.

**Comment by Feneg** [comment]
Thanks. I certainly plan to update this (at least once I've got some time again).

**Comment by Feneg** [comment]
Update has been pushed.
